Fix to prevent FaIR trying to run aggregated CO2
openscm/openscm-runner pull request #33
Opened 2020-12-04 09:02 UTC by chrisroadmap

See https://github.com/openscm/openscm-runner/issues/32

- [ ] Tests added
- [ ] Documentation added
- [ ] Example added (in the documentation, to an existing notebook, or in a new notebook)
- [ ] Description in ``CHANGELOG.rst`` added (single line such as: ``(`#XX <https://github.com/openscm/openscm-runner/pull/XX>`_) Added feature which does something``)

@rgieseke does this do the job?

2020-12-04 09:05 UTC, chrisroadmap commented
If there's a scenario you have as a test case, I can add it to the tests to make sure this works.

2020-12-04 09:20 UTC, rgieseke commented
Checking it out right now, thanks for the quick reply! (And sorry for not providing a reproducible case right away...)

2020-12-04 10:19 UTC, rgieseke commented
I've tried adding a failing test and test scenario in #34. In the RCMIP Phase 1 input data, there are multiple examples of summarizing emissions (e.g. for N2O as well), so only checking for CO2 is not enough.

2020-12-04 16:24 UTC, chrisroadmap commented
> (e.g. for N2O as well)

FaIR does want to use the aggregated N2O and ignore the AFOLU / FF+I individual totals. Same as for other species e.g. the aerosols with multiple sectors.

2020-12-04 16:25 UTC, chrisroadmap commented
How should I/we attack this @rgieseke ? Rebase #34 onto this and work from here?

2020-12-04 16:32 UTC, rgieseke commented
> How should I/we attack this @rgieseke ? Rebase #34 onto this and work from here?

As you like (sorry for causing more confusion by opening another PR).

2020-12-04 16:37 UTC, rgieseke commented
> FaIR does want to use the aggregated N2O and ignore the AFOLU / FF+I individual totals. Same as for other species e.g. the aerosols with multiple sectors.

Yes, for a dataset with multiple aggregated emissions (like RCMIP input) only checking for `|CO2` is not enough.

Without the fix here:
```
pint.errors.DimensionalityError: Cannot convert from 'CO2 * megametric_ton / a' ([carbon] * [mass] / [time]) to 'megatCO / a' ([carbon_monoxide] * [mass] / [time])
```

With the check for `|CO2`:
```
pint.errors.DimensionalityError: Cannot convert from 'CO * megametric_ton / a' ([carbon_monoxide] * [mass] / [time]) to 'gigatC / a' ([carbon] * [mass] / [time])
```

2020-12-07 12:13 UTC, chrisroadmap commented
I've got no idea what's going on here. Why is it trying to convert CO units?

2020-12-07 12:58 UTC, chrisroadmap commented
Think I got it

2020-12-07 13:41 UTC, rgieseke commented
Looks good to me, thanks for looking into it!

2020-12-08 07:12 UTC, rgieseke commented
Can you rebase that on master @chrisroadmap?

I think then we can merge it @znicholls

2020-12-08 07:23 UTC, znicholls requested changes

2020-12-08 07:23 UTC, znicholls commented on src/openscm_runner/adapters/fair_adapter/_scmdf_to_emissions.py
> +        # for scenarios providing both aggregate fossil and AFOLU CO2, ignore the total
```suggestion
        # for scenarios providing total CO2, ignore the total
```

2020-12-08 07:23 UTC, znicholls commented on src/openscm_runner/adapters/fair_adapter/_scmdf_to_emissions.py
> +        # we don't care about the split for most emitted species
```suggestion
        # we don't care about the split below the AFOLU and Fossil levels
```

2020-12-08 07:23 UTC, znicholls commented on src/openscm_runner/adapters/fair_adapter/_scmdf_to_emissions.py
> +        if variable.endswith(
```suggestion
        if "MAGICC AFOLU|" in variable or "MAGICC Fossil and Industrial|" in variable
```

should do the same thing and means you only need one line

2020-12-08 07:23 UTC, znicholls commented on src/openscm_runner/adapters/fair_adapter/_scmdf_to_emissions.py
> +        # except we do want fossil and AFOLU separate for CO2
```suggestion
        # we do want fossil and AFOLU separate for CO2
```

2020-12-08 07:23 UTC, znicholls commented on tests/unit/test_fair1x_utils.py
> +# 'Emissions|CO2' (which is summarizing 'MAGICC Fossil
```suggestion
# 'Emissions|CO2' (which is the total CO2 emissions
```

line below can be deleted too

2020-12-08 07:23 UTC, znicholls commented on tests/unit/test_fair1x_utils.py
> +    assert emissions.shape[1] == 40
worth checking any CO2 AFOLU and CO2 Fossil values?

2020-12-08 08:44 UTC, rgieseke commented
I'm wondering whether checking against the "allowed" values could be easier and future-proof against renaming scenario variables.

I'll give this a try @chrisroadmap

2020-12-08 22:42 UTC, znicholls commented
Close in favour of #37?

2020-12-09 08:10 UTC, closed without merging